<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template name="currency">
	<!-- main order -->
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ALL'"><span>&#x4c;&#x65;&#x6b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='AFN'"><span>&#x60b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ARS'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='AWG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='AUD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='AZN'"><span>&#x43c;&#x430;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BSD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BYR'"><span>&#x70;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BMD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BOB'"><span>&#x24;&#x62;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BAM'"><span>&#x4b;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BWP'"><span>&#x50;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BGN'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BRL'"><span>&#x52;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='BND'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KHR'"><span>&#x17db;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CLP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CNY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='COP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CRC'"><span>&#x20a1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='HRK'"><span>&#x6b;&#x6e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CUP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CZK'"><span>&#x4b;&#x10d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='DKK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='DOP'"><span>&#x52;&#x44;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='XCD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='EGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SVC'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='EEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='EUR'"><span>&#x20ac;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='FKP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='FJD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='GHC'"><span>&#xa2;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='GIP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='GTQ'"><span>&#x51;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='GGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='GYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='HNL'"><span>&#x4c;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='HKD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='HUF'"><span>&#x46;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ISK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='IDR'"><span>&#x52;&#x70;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='IRR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='IMP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ILS'"><span>&#x20aa;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='JMD'"><span>&#x4a;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='JPY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='JEP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KZT'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KGS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='LAK'"><span>&#x20ad;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='LVL'"><span>&#x4c;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='LBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='LRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='LTL'"><span>&#x4c;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='MKD'"><span>&#x434;&#x435;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='MYR'"><span>&#x52;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='MUR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='MXN'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='MNT'"><span>&#x20ae;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='MZN'"><span>&#x4d;&#x54;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='NAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='NPR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ANG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='NZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='NIO'"><span>&#x43;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='NGN'"><span>&#x20a6;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='NOK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='OMR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='PKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='PAB'"><span>&#x42;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='PYG'"><span>&#x47;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='PEN'"><span>&#x53;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='PHP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='PLN'"><span>&#x7a;&#x142;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='QAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='RON'"><span>&#x6c;&#x65;&#x69;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='RUB'"><span>&#x440;&#x443;&#x431;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SHP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='RSD'"><span>&#x414;&#x438;&#x43d;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SCR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SGD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SOS'"><span>&#x53;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ZAR'"><span>&#x52;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='LKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='CHF'"><span>&#x43;&#x48;&#x46;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='SYP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='TWD'"><span>&#x4e;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='THB'"><span>&#xe3f;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='TTD'"><span>&#x54;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='TRL'"><span>&#x20a4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='TVD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='UAH'"><span>&#x20b4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='GBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='USD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='UYU'"><span>&#x24;&#x55;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='UZS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='VEF'"><span>&#x42;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='VND'"><span>&#x20ab;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='YER'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Order/OrderHeader/Currency='ZWD'"><span>&#x24;</span></xsl:if>

	<!-- returned -->
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ALL'"><span>&#x4c;&#x65;&#x6b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='AFN'"><span>&#x60b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ARS'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='AWG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='AUD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='AZN'"><span>&#x43c;&#x430;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BSD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BYR'"><span>&#x70;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BMD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BOB'"><span>&#x24;&#x62;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BAM'"><span>&#x4b;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BWP'"><span>&#x50;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BGN'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BRL'"><span>&#x52;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='BND'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KHR'"><span>&#x17db;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CLP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CNY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='COP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CRC'"><span>&#x20a1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='HRK'"><span>&#x6b;&#x6e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CUP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CZK'"><span>&#x4b;&#x10d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='DKK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='DOP'"><span>&#x52;&#x44;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='XCD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='EGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SVC'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='EEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='EUR'"><span>&#x20ac;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='FKP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='FJD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='GHC'"><span>&#xa2;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='GIP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='GTQ'"><span>&#x51;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='GGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='GYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='HNL'"><span>&#x4c;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='HKD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='HUF'"><span>&#x46;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ISK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='IDR'"><span>&#x52;&#x70;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='IRR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='IMP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ILS'"><span>&#x20aa;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='JMD'"><span>&#x4a;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='JPY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='JEP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KZT'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KGS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='LAK'"><span>&#x20ad;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='LVL'"><span>&#x4c;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='LBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='LRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='LTL'"><span>&#x4c;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='MKD'"><span>&#x434;&#x435;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='MYR'"><span>&#x52;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='MUR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='MXN'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='MNT'"><span>&#x20ae;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='MZN'"><span>&#x4d;&#x54;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='NAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='NPR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ANG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='NZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='NIO'"><span>&#x43;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='NGN'"><span>&#x20a6;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='NOK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='OMR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='PKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='PAB'"><span>&#x42;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='PYG'"><span>&#x47;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='PEN'"><span>&#x53;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='PHP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='PLN'"><span>&#x7a;&#x142;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='QAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='RON'"><span>&#x6c;&#x65;&#x69;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='RUB'"><span>&#x440;&#x443;&#x431;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SHP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='RSD'"><span>&#x414;&#x438;&#x43d;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SCR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SGD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SOS'"><span>&#x53;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ZAR'"><span>&#x52;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='LKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='CHF'"><span>&#x43;&#x48;&#x46;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='SYP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='TWD'"><span>&#x4e;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='THB'"><span>&#xe3f;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='TTD'"><span>&#x54;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='TRL'"><span>&#x20a4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='TVD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='UAH'"><span>&#x20b4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='GBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='USD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='UYU'"><span>&#x24;&#x55;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='UZS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='VEF'"><span>&#x42;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='VND'"><span>&#x20ab;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='YER'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/ReturnDetails/ReturnedItems/ReturnedItem/Currency='ZWD'"><span>&#x24;</span></xsl:if>

	<!-- refunded -->
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ALL'"><span>&#x4c;&#x65;&#x6b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='AFN'"><span>&#x60b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ARS'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='AWG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='AUD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='AZN'"><span>&#x43c;&#x430;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BSD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BYR'"><span>&#x70;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BMD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BOB'"><span>&#x24;&#x62;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BAM'"><span>&#x4b;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BWP'"><span>&#x50;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BGN'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BRL'"><span>&#x52;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='BND'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KHR'"><span>&#x17db;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CLP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CNY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='COP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CRC'"><span>&#x20a1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='HRK'"><span>&#x6b;&#x6e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CUP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CZK'"><span>&#x4b;&#x10d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='DKK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='DOP'"><span>&#x52;&#x44;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='XCD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='EGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SVC'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='EEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='EUR'"><span>&#x20ac;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='FKP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='FJD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='GHC'"><span>&#xa2;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='GIP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='GTQ'"><span>&#x51;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='GGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='GYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='HNL'"><span>&#x4c;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='HKD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='HUF'"><span>&#x46;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ISK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='IDR'"><span>&#x52;&#x70;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='IRR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='IMP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ILS'"><span>&#x20aa;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='JMD'"><span>&#x4a;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='JPY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='JEP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KZT'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KGS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='LAK'"><span>&#x20ad;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='LVL'"><span>&#x4c;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='LBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='LRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='LTL'"><span>&#x4c;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='MKD'"><span>&#x434;&#x435;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='MYR'"><span>&#x52;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='MUR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='MXN'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='MNT'"><span>&#x20ae;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='MZN'"><span>&#x4d;&#x54;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='NAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='NPR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ANG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='NZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='NIO'"><span>&#x43;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='NGN'"><span>&#x20a6;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='NOK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='OMR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='PKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='PAB'"><span>&#x42;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='PYG'"><span>&#x47;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='PEN'"><span>&#x53;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='PHP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='PLN'"><span>&#x7a;&#x142;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='QAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='RON'"><span>&#x6c;&#x65;&#x69;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='RUB'"><span>&#x440;&#x443;&#x431;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SHP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='RSD'"><span>&#x414;&#x438;&#x43d;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SCR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SGD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SOS'"><span>&#x53;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ZAR'"><span>&#x52;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='LKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='CHF'"><span>&#x43;&#x48;&#x46;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='SYP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='TWD'"><span>&#x4e;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='THB'"><span>&#xe3f;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='TTD'"><span>&#x54;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='TRL'"><span>&#x20a4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='TVD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='UAH'"><span>&#x20b4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='GBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='USD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='UYU'"><span>&#x24;&#x55;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='UZS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='VEF'"><span>&#x42;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='VND'"><span>&#x20ab;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='YER'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/RefundDetails/RefundedItems/RefundedItem/Currency='ZWD'"><span>&#x24;</span></xsl:if>

	<!-- other -->
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ALL'"><span>&#x4c;&#x65;&#x6b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='AFN'"><span>&#x60b;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ARS'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='AWG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='AUD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='AZN'"><span>&#x43c;&#x430;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BSD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BYR'"><span>&#x70;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BMD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BOB'"><span>&#x24;&#x62;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BAM'"><span>&#x4b;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BWP'"><span>&#x50;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BGN'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BRL'"><span>&#x52;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='BND'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KHR'"><span>&#x17db;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CLP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CNY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='COP'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CRC'"><span>&#x20a1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='HRK'"><span>&#x6b;&#x6e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CUP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CZK'"><span>&#x4b;&#x10d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='DKK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='DOP'"><span>&#x52;&#x44;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='XCD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='EGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SVC'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='EEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='EUR'"><span>&#x20ac;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='FKP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='FJD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='GHC'"><span>&#xa2;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='GIP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='GTQ'"><span>&#x51;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='GGP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='GYD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='HNL'"><span>&#x4c;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='HKD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='HUF'"><span>&#x46;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ISK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='IDR'"><span>&#x52;&#x70;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='IRR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='IMP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ILS'"><span>&#x20aa;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='JMD'"><span>&#x4a;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='JPY'"><span>&#xa5;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='JEP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KZT'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KGS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='LAK'"><span>&#x20ad;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='LVL'"><span>&#x4c;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='LBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='LRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='LTL'"><span>&#x4c;&#x74;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='MKD'"><span>&#x434;&#x435;&#x43d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='MYR'"><span>&#x52;&#x4d;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='MUR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='MXN'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='MNT'"><span>&#x20ae;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='MZN'"><span>&#x4d;&#x54;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='NAD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='NPR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ANG'"><span>&#x192;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='NZD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='NIO'"><span>&#x43;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='NGN'"><span>&#x20a6;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KPW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='NOK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='OMR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='PKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='PAB'"><span>&#x42;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='PYG'"><span>&#x47;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='PEN'"><span>&#x53;&#x2f;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='PHP'"><span>&#x20b1;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='PLN'"><span>&#x7a;&#x142;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='QAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='RON'"><span>&#x6c;&#x65;&#x69;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='RUB'"><span>&#x440;&#x443;&#x431;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SHP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SAR'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='RSD'"><span>&#x414;&#x438;&#x43d;&#x2e;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SCR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SGD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SBD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SOS'"><span>&#x53;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ZAR'"><span>&#x52;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='KRW'"><span>&#x20a9;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='LKR'"><span>&#x20a8;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SEK'"><span>&#x6b;&#x72;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='CHF'"><span>&#x43;&#x48;&#x46;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SRD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='SYP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='TWD'"><span>&#x4e;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='THB'"><span>&#xe3f;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='TTD'"><span>&#x54;&#x54;&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='TRL'"><span>&#x20a4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='TVD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='UAH'"><span>&#x20b4;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='GBP'"><span>&#xa3;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='USD'"><span>&#x24;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='UYU'"><span>&#x24;&#x55;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='UZS'"><span>&#x43b;&#x432;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='VEF'"><span>&#x42;&#x73;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='VND'"><span>&#x20ab;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='YER'"><span>&#xfdfc;</span></xsl:if>
	<xsl:if test="/SFEmailMessages/EmailDataArea/Currency='ZWD'"><span>&#x24;</span></xsl:if>
</xsl:template>

</xsl:stylesheet>